---
kind: pipeline
type: docker
name: default

steps:
- name: check
  image: golang:1.18.6
  commands:
  - make check
  volumes:
  - name: gopath
    path: /go
- name: test
  image: golang:1.18.6
  commands:
  - make test
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

---
kind: pipeline
type: docker
name: GCR release

steps:
- name: Release to GCR
  image: plugins/gcr
  settings:
    repo: qa-setup/go_sdk_wrapper
    registry: us.gcr.io
    tags:
      - latest
      - ${DRONE_TAG}
    dockerfile: docker/Dockerfile
    json_key:
      from_secret: ff-gcp

trigger:
  ref:
  - "refs/tags/*"
  
---
kind: pipeline
type: docker
name: GCR manual release

steps:
- name: Release to GCR
  image: plugins/gcr
  settings:
    repo: qa-setup/go_sdk_wrapper
    registry: us.gcr.io
    tags:
      - ${DRONE_DEPLOY_TO}
    dockerfile: docker/Dockerfile
    json_key:
      from_secret: ff-gcp

trigger:
  event:
    - promote
...
