// Package metricsclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package metricsclient

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for MetricsDataMetricsType.
const (
	MetricsDataMetricsTypeFFMETRICS MetricsDataMetricsType = "FFMETRICS"
)

// Error defines model for Error.
type Error struct {
	// Code The http error code
	Code string `json:"code"`

	// Details Additional details about the error
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message The reason the request failed
	Message string `json:"message"`
}

// KeyValue defines model for KeyValue.
type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Metrics defines model for Metrics.
type Metrics struct {
	MetricsData *[]MetricsData `json:"metricsData,omitempty"`
	TargetData  *[]TargetData  `json:"targetData,omitempty"`
}

// MetricsData defines model for MetricsData.
type MetricsData struct {
	Attributes []KeyValue `json:"attributes"`
	Count      int        `json:"count"`

	// MetricsType This can be of type FeatureMetrics
	MetricsType MetricsDataMetricsType `json:"metricsType"`

	// Timestamp time at when this data was recorded
	Timestamp int64 `json:"timestamp"`
}

// MetricsDataMetricsType This can be of type FeatureMetrics
type MetricsDataMetricsType string

// TargetData defines model for TargetData.
type TargetData struct {
	Attributes []KeyValue `json:"attributes"`
	Identifier string     `json:"identifier"`
	Name       string     `json:"name"`
}

// ClusterQueryOptionalParam defines model for clusterQueryOptionalParam.
type ClusterQueryOptionalParam string

// EnvironmentPathParam defines model for environmentPathParam.
type EnvironmentPathParam string

// InternalServerError defines model for InternalServerError.
type InternalServerError Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated Error

// Unauthorized defines model for Unauthorized.
type Unauthorized Error

// PostMetricsParams defines parameters for PostMetrics.
type PostMetricsParams struct {
	// Cluster Unique identifier for the cluster for the account
	Cluster *ClusterQueryOptionalParam `form:"cluster,omitempty" json:"cluster,omitempty"`
}

// PostMetricsJSONRequestBody defines body for PostMetrics for application/json ContentType.
type PostMetricsJSONRequestBody Metrics
