pipeline:
  identifier: Build_ff_golang_server_sdk_1718706424778
  name: Build ff-golang-server-sdk
  orgIdentifier: default
  projectIdentifier: DavesProject
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.ffgitsync
        repoName: ff-golang-server-sdk
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Sh
                    command: echo "Building Go"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
