// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package restapi

// Error Status for wrapper
type ErrorResponse struct {
	ErrorMessage string `json:"error_message"`
}

// Request to check flag in SDK
type FlagCheckBody struct {
	FlagKey  string `json:"flag_key"`
	FlagKind string `json:"flag_kind"`
	Target   *struct {
		Attributes *struct {
			Email    *string `json:"email,omitempty"`
			Region   *string `json:"region,omitempty"`
			Username *string `json:"username,omitempty"`
		} `json:"attributes,omitempty"`
		TargetIdentifier *string `json:"target_identifier,omitempty"`
		TargetName       *string `json:"target_name,omitempty"`
	} `json:"target,omitempty"`
}

// Response to flag check in SDK
type FlagCheckResponse struct {
	FlagKey   string `json:"flag_key"`
	FlagValue string `json:"flag_value"`
}

// Response to Ping
type PongResponse struct {
	Pong bool `json:"pong"`
}

// GetFlagValueJSONBody defines parameters for GetFlagValue.
type GetFlagValueJSONBody FlagCheckBody

// GetFlagValueJSONRequestBody defines body for GetFlagValue for application/json ContentType.
type GetFlagValueJSONRequestBody GetFlagValueJSONBody
